### ISSUE TITLE
Do not do his job and prevent the pickaxe from doing his job

### ISSUE THREAD

**Issue by Unsomniaque** [arlyon/veining#6] opened 2018-01-30 06:21 UTC
## Version Information
Minecraft 1.12.2
forge-1.12.2-14.23.1.2607
veining-1.2.0-1.12.2
=>"veining" is the only mod installed for this test. The configuration file has not been modified.

## Report Information
An enchanted pick with veining breaks the stone (all sorts) but makes it disappear into nothingness (no loot). It breaks the minerals but only one by one like a normal pick.

## Steps to Reproduce
Enchant a pick with veining then go mine.

## Crash Log
no

## Forge Log
https://pastebin.com/TPfsjySf

**Comment by arlyon** [comment] 2018-01-30 18:23
Interesting I am on the same exact forge version with only the enchant and can't reproduce. I'll keep looking and see if I can figure it out. Thanks for the nicely formatted report by the way. If you don't mind, I'll create an issue template from it.

**Comment by Unsomniaque** [comment] 2018-01-30 19:05
I tested with the enchantment "veining" alone on the pickaxe, like you.
I specify that the version 1.1.0 of your mod works correctly (except for the XP) on the same platform of test. For information I use MultiMC Version 0.6.1-1177 with LWJGL2 2.9.4-nightly-20150209. The memory settings are : min 4096MB max 5120 MB permgen 256MB (I know it's a lot for the test but it's my basic setting for my modpack). No worries for the model.
Good luck for debugging :-)

**Comment by Unsomniaque** [comment] 2018-02-02 06:12
If you can not reproduce this bug, can you describe to me exactly your test platform (software) so that I try to reproduce the good functioning at home? Maybe it will allow me to find a "problem" in my own configuration.

**Comment by arlyon** [comment] 2018-02-04 12:14
Identical to you. Same forge, mc, mod version. Running on mac os. I just install forge from the installer and run from the minecraft launcher.

> java version "1.8.0_144"
> Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
> Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

edit:

I think I've found the issue that caused this issue and #5 as well. Going to test it and release a new version soon.

**Comment by Unsomniaque** [comment] 2018-02-06 01:33
Version 1.2.1 works perfectly at home, blocks and xp fall correctly.
Thank you for your work.

**Comment by arlyon** [comment] 2018-02-07 15:30
Great! I'll mark them as proper releases then. Closing this now.

**Closed as completed by arlyon** 2018-02-07 15:30 UTC
Labels: bug, duplicate

**Comment by border999** [comment] 2018-05-06 22:33
https://github.com/WayofTime/BloodMagic/issues/1300#issuecomment-386916153

**Comment by border999** [comment] 2018-05-06 22:33
https://github.com/arlyon/veining/issues/11
